title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sai-kumar-neelam-6691a5ab/">LinkedIn</a> |
  <a href="https://github.com/saikumar-neelam">GitHub</a>
  
  <br>   
  I'm a programmer at Tanla and as an AI enthusiast i will be working on the mentioned projects.
  <br>
  </p>



theme: jekyll-theme-minimal